# Generated by Django 5.1.2 on 2024-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_category_created_at_category_updated_at_post_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="rating",
            field=models.SmallIntegerField(default=0),
        ),
    ]
