# Generated by Django 5.1.2 on 2024-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_alter_postvote_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvote",
            name="value",
            field=models.SmallIntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
    ]
